const products = [
  {
    id: 0,
    title: "Base Plate Short Sleeve T-Shirt",
    slug: "t-shirt=men-base-plate-blended-short-sleeve",
    price: 34,
    color: ["light grey heather", " sandstone"],
    size: ["xl", "m", "s"],
    imgUrl: "/Men's Base Plate Blended Short Sleeve T-Shirt.jpg",
    desc: "71% Cotton, 29% Polyester.Imported.Pull On closure.Machine Wash.Timberland PRO's shirts make a serious function statement by offering wicking technologies plus comfort features, such as side-seam construction, bi-swing backs and tagless neck lables. Seasonal layering, Made comfortable and easy.Wicking polyester next-to-skin with rugged cotton face.Built-in 30+ UPF protection.TIMBERLAND PRO: Timberland PRO work shirts, work pants, jackets, shirts & more are made with the quality you've come to expect from Timberland PRO.",
    rating: 4.6,
    category: "men",
  },
  {
    id: 1,
    title: "Long Sleeve Mixed Material Shirt",
    slug: "t-shirt=men-long-sleeve-mixed-material",
    price: 54,
    color: ["vintage indigo"],
    size: ["xl", "m", "s"],
    imgUrl: "/Men's Long Sleeve Mixed Material Shirt.jpg",
    desc: "73% Nylon, 27% Polyester.Imported.Button closure.Machine Wash.MOISTURE WICKING. Made from a breathable mixed material utility blend, this shirt is designed to pull moisture away from the skin to keep you comfortable and dry during any activity. A vented back helps increase airflow.KNIT CONSTRUCTION. Contrast knit panels at the sides and sleeve allow extra stretch and ease of movement. A patent pending convertible sleeve system allows you to adjust the length.UV PROTECTION. UPF 30 offers built-in UV protection from the sun's harmful rays. Perfect for hiking to your favorite fishing spot, or out on the water, this shirt is ready for anything.",
    rating: 4.6,
    category: "men",
  },
  {
    id: 2,
    title: "Golf Short Sleeve Polo Shirt",
    slug: "t-shirt=men-performance-golf-grid-short-sleeve",
    price: 98.99,
    color: ["caneel bay", "candy pink"],
    size: ["xl", "m", "s"],
    imgUrl:
      "/Men's Performance Golf Grid Short Sleeve Stretch Polo Shirt-Legacy.jpg",
    desc: "100% Polyester.Short sleeve polo in tonal grid pattern featuring three-button placket and embroidered logo at left chest.Moisture wicking properties pull moisture away from the body keeping you dry and feeling cool.Swing Flex 4-Way Stretch fabric stretches both crosswise and lengthwise, allowing for maximum comfort in all directions, especially when perfecting your swing.Sun-Control with UPF-15 UV protective technology, so you can look sharp without worrying about the sun’s harmful rays.Easy care allows you to throw these on after washing",
    rating: 4.6,
    category: "men",
  },
  {
    id: 3,
    title: "Men's Short Sleeve Paris Polo",
    slug: "t-shirt=men-short-sleeve-paris-polo",
    price: 94.52,
    color: ["white", "black", "navy blue"],
    size: ["xl", "m", "s"],
    imgUrl: "/Men's Short Sleeve Paris Polo.jpg",
    desc: "100% Cotton.Button closure.A trim silhouette in between our 'Classic Fit' and 'Slim Fit'.Concealed two button placket for a sleek tailored finish.Ribbed polo collar and armbands.Tennis tail designed to stay tucked in.",
    rating: 4.6,
    category: "men",
  },
  {
    id: 4,
    title: "Women’s Stretch Cotton Tee",
    slug: "t-shirt=women-stretch-cotton-tee",
    price: 15.15,
    color: ["paleo pink", "black", "gray heather"],
    size: ["xl", "m", "s"],
    imgUrl: "/Women’s Stretch Cotton Tee.jpg",
    desc: "Women’s stretch cotton tee is made from super soft cotton-rich fabric. The comfortable fabric offers move-with-you style you’re sure to love.A flattering design, this cotton sleeve tee is designed with a wide, feminine scoop neckline.We recommends machine washing this women's shirt in cold water to help reduce energy consumption.",
    rating: 4.6,
    category: "women",
  },
  {
    id: 5,
    title: "Long Sleeve Turtleneck Shirt",
    slug: "t-shirt=women-long-sleeve-turtleneck-tee",
    price: 29.99,
    color: ["june bug", "true black", "white global"],
    size: ["xl", "m", "s"],
    imgUrl: "/Women's Long Sleeve Turtleneck Shirt.jpg",
    desc: "Dress-easy in the all-day comfort of this cotton top.long sleeve shirts are the ideal wardrobe staple.Easy to care for; this tee can be washed with like colors on the gentle cycle.Machine Wash.Imported stuff.",
    rating: 4.6,
    category: "women",
  },
  {
    id: 6,
    title: "Luxe Long Sleeve Neck T-Shirt",
    slug: "t-shirt=women-luxe-long-sleeve-crew-neck-tee",
    price: 34.95,
    color: ["black", "white", "pink"],
    size: ["xl", "m", "s"],
    imgUrl: "/Women's Luxe Long Sleeve Crew Neck Tee T-Shirt.jpg",
    desc: "95% Rayon, 5% Spandex.A plain long sleeve crewneck pullover that is a great addition to your wardrobe.The luxe jersey knit is soft, stretchy and won't shrink or fade from being washed.Easy to care for, this top can be washed with like colors on the gentle cycle.Imported.",
    rating: 4.6,
    category: "women",
  },
  {
    id: 7,
    title: "Women's Ribbed Long Sleeve Tee",
    slug: "t-shirt=women-ribbed-long-sleeve-tee",
    price: 122.27,
    color: ["black", "white"],
    size: ["xl", "m", "s"],
    imgUrl: "/Women's Ribbed Long Sleeve Tee.jpg",
    desc: "96% Modal, 4% Spandex.Luxe micro-rib knit with stretch.Won't shrink or fade from being washed.",
    rating: 4.6,
    category: "women",
  },
  {
    id: 30,
    title: "Asymmetric Cotton T-Shirt",
    slug: "t-shirt=teen-asymmetric-cotton",
    price: 55.99,
    color: ["off white", "sky blue"],
    size: ["xl", "m", "s"],
    imgUrl: "/Asymmetric cotton T-shirt.webp",
    desc: "100% Cotton. Light fabric. Plain fabric. Asymmetric design. Off-shoulder design. A sleeve. Bands details. Puffed sleeves. The model is 172 cm tall and is wearing a size M.",
    rating: 4.6,
    category: "teen",
  },
  {
    id: 29,
    title: "Ribed Short T-Shirt",
    slug: "t-shirt=teen-ribed-short",
    price: 67,
    color: ["black"],
    size: ["xl", "m", "s"],
    imgUrl: "/Ribed short t-shirt.webp",
    desc: "Basics Collection. 100% Cotton. Cable knit. Cropped design. Tailored design. Rounded neck. Short sleeve. The model is 172 cm tall and is wearing a size M.",
    rating: 4.6,
    category: "teen",
  },
  {
    id: 28,
    title: "Wide Strap T-Shirt",
    slug: "wide-strap-t-shirt-teen",
    price: 35.99,
    color: ["Sky Blue"],
    size: ["xl", "m", "s"],
    imgUrl: "/wide strap shirt.webp",
    desc: "Basics Collection. Cotton fabric. Elastic. Tailored dress. Standard design. Closed neck. Wide straps.",
    rating: 4.6,
    category: "teen",
  },
  {
    id: 28,
    title: "Striped Rib T-Shirt",
    slug: "t-shirt=teen-striped-rib",
    price: 35.99,
    color: ["mustard"],
    size: ["xl", "m", "s"],
    imgUrl: "/Striped Rib T-Shirt.jfif",
    desc: "Cable knit fabric. Slim fit. Turtleneck. Long sleeve. Standard design. The model is 172 cm tall and is wearing a size M.",
    rating: 4.6,
    category: "teen",
  },
  {
    id: 8,
    title: "Boys Cotton Long Sleeve T-Shirt",
    slug: "t-shirt=kids-heavy-cotton-long-sleeve",
    price: 98,
    color: ["carolina blue"],
    size: ["xl", "m", "s"],
    imgUrl: "/Boys Heavy Cotton Long Sleeve T-Shirt.jpg",
    desc: "100% Cotton.Made in the USA or Imported.Pull On closure.Machine Wash.Machine wash warm, inside out, with like colors. Only non-chlorine bleach. Tumble dry medium. Do not iron. Do not dry clean.seamless rib at neck.Taped shoulder-to-shoulder.",
    rating: 4.6,
    category: "teen",
  },
  {
    id: 9,
    title: "Uniform Short Sleeve Pique Polo",
    slug: "t-shirt=teen-uniform-short-sleeve-stretch-pique-polo",
    price: 67,
    color: ["white", "black"],
    size: ["xl", "m", "s"],
    imgUrl: "/Young Men's Uniform Short Sleeve Stretch Pique Polo.jpg",
    desc: "64% Cotton, 36% Polyester.Imported.Button closure.Machine Wash.Meet uniform requirements with Nautica solid polos made from breathable stretch cotton and durable polyester to deliver all-day comfort.This solid and free-of-logos polo design features ribbing at the cuffs and collar, button placket, short sleeves and straight vented hems .Available in a variety of colors and sizes.Easy care and designed to match any bottom type while ensuring quality, fit and comfort.",
    rating: 4.6,
    category: "teen",
  },
  {
    id: 26,
    title: "Outdoor Crew Neck Graphic T-Shirt",
    slug: "t-shirt=teen-short-sleeve-crew-neck-graphic",
    price: 97,
    color: ["orange"],
    size: ["xl", "m", "s"],
    imgUrl: "/Outdoor Boys' Short Sleeve Crew Neck Graphic T-Shirt.jpg",
    desc: "93% Polyester, 7% Spandex.Imported.Pull On closure.Machine Wash.A classic staple for any boys' wardrobe featuring short sleeves, a crew neckline, and logo graphics on the chest.Soft, simple and stylish, pairs well with anything from casual jeans to dressy slacks.We use high-quality materials in all our kids clothing to ensure maximum comfort, longevity and lasting power.Available in Big Boys’ sizes 8 to 20.Offers iconic style season after season with unique designs and signature logos.",
    rating: 4.6,
    category: "teen",
  },
  {
    id: 11,
    title: "Boys'Graphic Crew Neck T-Shirt",
    slug: "t-shirt=kids-",
    price: 60,
    color: ["pomegrante filled"],
    size: ["xl", "m", "s"],
    imgUrl: "/Boys' Long Sleeve Graphic Crew Neck T-Shirt.jpg",
    desc: "100% CottonImported.Pull On closure.Machine Wash.Branded with modern logo graphics, this soft jersey tee by Nautica delivers easy comfort and signature style for everyday dressing.Long sleeve.Crew-neck, ribbed trim.",
    rating: 4.6,
    category: "teen",
  },
  {
    id: 12,
    title: "Girls'Round Neck Cotton T-Shirt",
    slug: "t-shirt=kids-basic-long-sleeve-round-neck",
    price: 23.69,
    color: ["brown"],
    size: ["xl", "m", "s"],
    imgUrl: "/Girls' Basic Long Sleeve Round Neck Cotton T-Shirt.jpg",
    desc: "Cotton,Elastane.Imported.Pull On closure.Machine Wash.Girls long sleeve crew neck soft and comfortable tee..Great for everyday wear.95% Cotton, 5% elastane. Size 2-12 years. Machine wash.",
    rating: 4.6,
    category: "kids",
  },
  {
    id: 13,
    title: "Long Sleeve Layering T-Shirt",
    slug: "t-shirt=kids-long-sleeve-basic-layering",
    price: 98.9,
    color: ["peach"],
    size: ["xl", "m", "s"],
    imgUrl: "/The Children's Place Girls' Long Sleeve Basic Layering T-Shirt.jpg",
    desc: "100% Cotton.Imported.Pull On closure.Machine Wash.Made of soft cotton for a comfortable, no-fuss feel all day long.Pull-over style with long sleeves and a crew neck.A closet must for any season, this top is cute under her favorite sweater or sported solo over a pair of shorts.The Children's Place offers value-priced clothes and apparel that are fun and easy to put together.They'll love this style…you'll love this place.",
    rating: 4.6,
    category: "kids",
  },
  {
    id: 22,
    title: "Champion Girls' Performance Tank",
    slug: "t-shirt=kids-champion-girl-performance-tank",
    price: 25.22,
    color: ["iced green tea heather"],
    size: ["xl", "m", "s"],
    imgUrl: "/Champion Girls' Performance Tank.jpg",
    desc: "Body: 100% Polyester; Piecing: 86% Polyester, 14% Spandex.Imported.Pull On closure.Machine Wash.Semi-fitted: body skimming fit.Duo Dry - wicks moisture, dries fast.Durable fabric stands up to repeated washings.Breathable fabric helps to keep you cool.Princess seams offer a flattering look.",
    rating: 4.6,
    category: "kids",
  },
  {
    id: 32,
    title: "Embossed Long-Sleeved T-Shirt",
    slug: "t-shirt=kids-embossed-long-sleeved",
    price: 21.99,
    color: ["medium heather grey"],
    size: ["xl", "m", "s"],
    imgUrl: "/Embossed long-sleeved t-shirt.webp",
    desc: "Cotton fabric. Embroidered message. Embossed detail. Cropped design. Rounded neck. Long sleeve.",
    rating: 4.6,
    category: "kids",
  },
  {
    id: 33,
    title: "Printed Long Sleeve T-Shirt",
    slug: "t-shirt=kids-printed-long-sleeve",
    price: 29.01,
    color: ["blue"],
    size: ["xl", "m", "s"],
    imgUrl: "/Printed long sleeve t-shirt.webp",
    desc: "100% cotton fabric. Printed design. Rounded neck. Long sleeve.",
    rating: 4.6,
    category: "kids",
  },
  {
    id: 34,
    title: "Printed Cotton Sweatshirt",
    slug: "t-shirt=kids-printed-cotton",
    price: 54,
    color: ["off white", "black"],
    size: ["xl", "m", "s"],
    imgUrl: "/Printed cotton sweatshirt.webp",
    desc: "100% Cotton. Printed design. Straight design. Rounded neck. Long sleeve.",
    rating: 4.6,
    category: "kids",
  },
  {
    id: 35,
    title: "Printed Cotton Shirt",
    slug: "t-shirt=kids-printed-cotton-sweat",
    price: 34,
    color: ["khaki"],
    size: ["xl", "m", "s"],
    imgUrl: "/Printed cotton shirt.webp",
    desc: "100% Cotton. Printed design. Straight design. Rounded neck. Long sleeve.",
    rating: 4.6,
    category: "kids",
  },
  {
    id: 36,
    title: "Cotton Long Sleeve Sweatshirt",
    slug: "t-shirt=kids-printed-cotton-long-sleeve",
    price: 22,
    color: ["vibrant blue"],
    size: ["xl", "m", "s"],
    imgUrl: "/Printed cotton long sleeve sweatshirt.webp",
    desc: "100% Cotton. Printed design. Straight design. Hood. Long sleeve. Pouch pocket.",
    rating: 4.6,
    category: "kids",
  },

]

const getProduct = (slug) => {
  let product = {}
  products.map((p) => {
    if (p.slug === slug) {
      product = p
    }
  })
  return product
}

// get slug from url
// const product = getProduct(slug)

export { getProduct }
export default products